"""PDF generation for the Audit Report (Session 3).

Uses reportlab to generate the Audit Report PDF.
Saves to Google Cloud Storage and returns the GCS URL.
"""

import asyncio
import io
import logging
from datetime import datetime, timezone

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib import colors
from reportlab.lib.units import mm

from models.audit import SynthesisReport

logger = logging.getLogger(__name__)


def generate_audit_pdf(report: SynthesisReport, creator_handle: str, creator_niche: str) -> bytes:
    """Generates the Audit Report PDF. Returns PDF bytes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=20*mm, bottomMargin=20*mm)
    styles = getSampleStyleSheet()
    story = []

    # Header
    story.append(Paragraph("ThreadComb Skills Audit", styles["Title"]))
    story.append(Paragraph(
        f"{creator_handle} · {creator_niche.title()} · {datetime.now(timezone.utc).strftime('%B %Y')}",
        styles["Normal"]
    ))
    story.append(Spacer(1, 10*mm))

    # Executive Summary
    story.append(Paragraph("Summary", styles["Heading2"]))
    story.append(Paragraph(report.executive_summary, styles["Normal"]))
    story.append(Spacer(1, 6*mm))

    # Total recoverable value
    if report.total_recoverable_value:
        story.append(Paragraph(
            f"Identified recoverable value: ₹{report.total_recoverable_value:,.0f}",
            styles["Heading3"]
        ))
    elif report.total_recoverable_unknown:
        story.append(Paragraph(
            "Recoverable value: Unknown (deal amounts not stated in emails — deal count tracked below)",
            styles["Normal"]
        ))
    story.append(Spacer(1, 8*mm))

    # Findings
    story.append(Paragraph("Findings", styles["Heading2"]))

    severity_colours = {
        "high": colors.HexColor("#A32D2D"),
        "medium": colors.HexColor("#BA7517"),
        "low": colors.HexColor("#378ADD"),
        "positive": colors.HexColor("#1D9E75"),
    }

    for finding in report.findings:
        colour = severity_colours.get(finding.severity, colors.black)
        story.append(Paragraph(finding.title, styles["Heading3"]))
        story.append(Paragraph(finding.finding_text, styles["Normal"]))
        if finding.value_inr:
            story.append(Paragraph(f"Value: ₹{finding.value_inr:,.0f}", styles["Normal"]))
        elif finding.value_unknown:
            story.append(Paragraph("Value: Amount not stated in emails", styles["Normal"]))
        story.append(Paragraph(f"Evidence: {finding.evidence}", styles["Italic"]))
        story.append(Paragraph(f"Recommendation: {finding.recommendation}", styles["Normal"]))
        story.append(Spacer(1, 5*mm))

    # Skills Map Summary
    if report.skills_map_summary:
        story.append(Spacer(1, 5*mm))
        story.append(Paragraph("Your Operational DNA", styles["Heading2"]))
        story.append(Paragraph(report.skills_map_summary, styles["Normal"]))

    # Data quality note
    if report.data_quality_note:
        story.append(Spacer(1, 5*mm))
        story.append(Paragraph("Note on Data Quality", styles["Heading3"]))
        story.append(Paragraph(report.data_quality_note, styles["Normal"]))

    # Footer
    story.append(Spacer(1, 10*mm))
    story.append(Paragraph(
        "Generated by ThreadComb · threadcomb.com · All data is derived from your own Gmail account.",
        styles["Normal"]
    ))

    doc.build(story)
    return buffer.getvalue()


async def upload_audit_pdf_to_gcs(pdf_bytes: bytes, creator_id: str) -> str:
    """Uploads PDF to GCS and returns the public URL.

    Falls back to returning a placeholder URL if GCS is not configured
    (e.g., during local development).
    """
    from config import settings

    if not settings.GCS_BUCKET_NAME:
        logger.warning("GCS_BUCKET_NAME not configured — skipping PDF upload")
        return f"local://audit_reports/{creator_id}/audit.pdf"

    try:
        from google.cloud import storage

        def _upload():
            client = storage.Client()
            bucket = client.bucket(settings.GCS_BUCKET_NAME)
            blob_name = f"audit_reports/{creator_id}/{datetime.now(timezone.utc).strftime('%Y%m')}_audit.pdf"
            blob = bucket.blob(blob_name)
            blob.upload_from_string(pdf_bytes, content_type="application/pdf")
            blob.make_public()
            return blob.public_url

        return await asyncio.to_thread(_upload)

    except Exception as e:
        logger.error(f"GCS upload failed for creator {creator_id}: {e}")
        # Return a fallback — the report is still stored in MongoDB
        return f"gcs_error://audit_reports/{creator_id}/audit.pdf"
