# backend/services/voice_compliance.py
"""
Call B — the separate voice compliance evaluator.
This function evaluates a draft without knowing it was generated by the Deal Chief.
It does NOT receive any context about what the draft is supposed to say.
It ONLY evaluates: does this draft sound like the creator's voice profile?
"""

import asyncio
import json
import logging
from models.draft import VoiceComplianceResult

logger = logging.getLogger(__name__)
EVALUATOR_MODEL = "gemini-2.5-flash"  # intentionally same model — different prompt, different session

VOICE_EVALUATOR_SYSTEM_PROMPT = """
You are evaluating whether an email draft matches a specific person's writing style.
You are NOT evaluating whether the content is correct, appropriate, or complete.
You are ONLY evaluating style: does this draft sound like someone with this voice profile?

Voice profile fields:
- formality_score: 1.0 (very casual) to 5.0 (very formal)
- emoji_frequency: average emojis per message
- avg_response_length: typical word count
- hindi_english_ratio: 0.0 = all English, 1.0 = all Hindi
- common_openers: phrases this person uses to start messages
- common_closers: phrases this person uses to end messages
- uses_caps_emphasis: does this person use ALL CAPS for emphasis?

Return JSON matching VoiceComplianceResult. Be specific about issues.
Score 1.0 = perfect match. Score below 0.75 = significant mismatch.
"""


async def evaluate_voice_compliance(
    draft_text: str,
    voice_profile: dict,
) -> VoiceComplianceResult:
    """
    Call B — evaluates draft against voice profile.
    Called separately from the draft generation (Call A).
    Never raises — returns a neutral score on any error.
    """
    from services.gemini_client import get_gemini_client_genai
    from google.genai import types
    client = get_gemini_client_genai()

    logger.info("Voice compliance evaluation: starting independent Gemini call (Call B)")

    evaluation_input = f"""
Voice profile to evaluate against:
{json.dumps(voice_profile, indent=2)}

Email draft to evaluate:
{draft_text}

Evaluate whether the draft matches this voice profile.
"""

    try:
        response = await asyncio.to_thread(
            client.models.generate_content,
            model=EVALUATOR_MODEL,
            contents=evaluation_input,
            config=types.GenerateContentConfig(
                system_instruction=VOICE_EVALUATOR_SYSTEM_PROMPT,
                response_mime_type="application/json",
                response_schema=VoiceComplianceResult,
                temperature=0.0,
                max_output_tokens=2048,
            )
        )
        if response.parsed:
            return response.parsed
        raise ValueError("Model completed successfully but output schema execution failed.")

    except Exception as e:
        logger.error(f"Voice compliance evaluation error: {e}")
        return VoiceComplianceResult(
            voice_compliance_score=0.5,
            formality_match=True,
            emoji_match=True,
            length_match=True,
            hindi_integration_correct=True,
            specific_issues=[f"Evaluation unavailable: {str(e)[:80]}"],
            overall_assessment="Could not evaluate — using draft as generated."
        )
